apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80    # Exposing on port 80
      targetPort: 3000 # Targeting the container's port 3000
  type: LoadBalancer # Or NodePort if you want to expose it differently
